export * from './account/account';
export * from './authorization/authorization';
export * from './edit/edit';
export * from './main/main';
export * from './question/question';
export * from './registration/registration';
export * from './result/result';
export * from './test/test';
export * from './user-tests/user-tests';
