export const ACTION_TYPE = {
	SET_TEST_DATA: 'SET_TEST_DATA',
	ADD_ANSWER: 'ADD_ANSWER',
	CHANGE_CORRECT_ANSWER: 'SET_CORRECT_ANSWER',
	DELETE_ANSWER: 'DELETE_ANSWER',
	UPDATE_ANSWER_TEXT: 'UPDATE_ANSWER_TEXT',
	ADD_QUESTION: 'ADD_QUESTION',
	DELETE_QUESTION: 'DELETE_QUESTION',
	UPDATE_QUESTION: 'UPDATE_QUESTION',
	UPDATE_QUESTION_TEXT: 'UPDATE_QUESTION_TEXT',
	OPEN_MODAL: 'OPEN_MODAL',
	CLOSE_MODAL: 'CLOSE_MODAL',
};
