name: Deploy to Hosting
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Latest Code
        uses: actions/checkout@v3

      - name: Deploy to Hosting
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 82.97.241.26
          remote-user: yi30181
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: ~/quiz/
